print("[score] [previous winner]:")
use = open("dicerol.txt", "a")
print(use.seekable())
use = open("dicerol.txt", "r")
print(use.readline())
print(use.readline())
print(use.readlines())
print(use.tell())
use.close()
print("done!")